/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ProdutoCollection;
import Model.ProdutoObserver;
import Presenter.InclusaoProdutoPresenter;
import javax.swing.JLabel;

/**
 *
 * @author Pedro Vitor
 */
public class telaPrincipal extends javax.swing.JFrame implements ProdutoObserver {
    
    private ProdutoCollection produtoCollection;

    public telaPrincipal(ProdutoCollection produtoCollection) {
        this.produtoCollection = produtoCollection;
        initComponents();
        produtoCollection.addObserver(this);
        update();
        mnAdicionarProduto.addActionListener(e -> onProdutoView());
        mnListarProduto.addActionListener(e -> onListarProdutoView());
    }
    
    private void onProdutoView() {
        new InclusaoProdutoPresenter(produtoCollection); 
    }
    private void onListarProdutoView() {
        new ListarProdutoView(produtoCollection).setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAdicionarProduto = new javax.swing.JMenu();
        mnListarProduto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatus.setText("Total de produtos: 0");

        jMenu1.setText("Menu");

        mnAdicionarProduto.setText("Incluir Produto");
        mnAdicionarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAdicionarProdutoMouseClicked(evt);
            }
        });
        jMenu1.add(mnAdicionarProduto);

        mnListarProduto.setText("Listar Produtos");
        mnListarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnListarProdutoMouseClicked(evt);
            }
        });
        jMenu1.add(mnListarProduto);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lblStatus)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lblStatus)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAdicionarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAdicionarProdutoMouseClicked
        onProdutoView();        
    }//GEN-LAST:event_mnAdicionarProdutoMouseClicked

    private void mnListarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnListarProdutoMouseClicked
        onListarProdutoView();        
    }//GEN-LAST:event_mnListarProdutoMouseClicked

    @Override
    public void update() {
        lblStatus.setText("Total de Produtos: " + produtoCollection.getProdutos().size());
    }
//     public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ProdutoCollection produtoCollection = new ProdutoCollection();
//                new telaPrincipal(produtoCollection).setVisible(true);
//            }
//        });
//    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenu mnAdicionarProduto;
    private javax.swing.JMenu mnListarProduto;
    // End of variables declaration//GEN-END:variables
}
